### ISSUE TITLE
Repeat faster, or let users adjust the speed 

### ISSUE THREAD

**Issue by hirako2000** [victorqribeiro/genius#1]
Post level 10, user attention is lost because the series was already memorised and the repetition is just too slow.

I suggest 
- speed up the repeat phase, and slow back to what it is right before last step.
Or (better) 
- allow users to speed up the step play, with some control from say 1 second down to 10ms lapse per step.

Thanks for this interesting memory game and for sharing it as open source!

**Comment by victorqribeiro** [comment]
I left the several speeds of the game as variables, so it's easy to adjust. I was originally thinking in increase the speed as the levels goes up, you know, to hardener the difficulty. But, what you suggesting is the opposite of what I was thinking. You're saying that it'll be easier to repeat the pattern if the computer shows it faster. is that it? As I said, it could be easily adjusted, I just wanna make sure that other players agree with you on this one.

**Comment by victorqribeiro** [comment]
I've added a slider so you can choose how fast you want the computer to play. no values to keep the design simple and minimalist
